#!/bin/bash

inputfile=$1

#!/bin/bash

ffmpeg -y -i "$inputfile" -pass 1 -s 236x200 -r 30000/1001 -b 70k -bt 70k -vcodec libx264 -vpre ipod320 -acodec libfaac -ac 2 -ar 48000 -ab 50k "$inputfile".mp4
ffmpeg -y -i "$inputfile" -pass 2 -s 236x200 -r 30000/1001 -b 70k -bt 70k -vcodec libx264 -vpre ipod320 -acodec libfaac -ac 2 -ar 48000 -ab 50k "$inputfile".mp4
ffmpeg -y -i "$inputfile" -pass 3 -s 236x200 -r 30000/1001 -b 70k -bt 70k -vcodec libx264 -vpre ipod320 -acodec libfaac -ac 2 -ar 48000 -ab 50k "$inputfile".mp4
ffmpeg2theora "$inputfile".mp4 -v 9 -a 5 "$inputfile".mp4.ogv
