#!/bin/bash

inputfile=$1

#!/bin/bash

ffmpeg -y -i "$inputfile" -pass 1 -b:v 0.7M "$inputfile".mp4
ffmpeg -y -i "$inputfile" -pass 2 -b:v 0.7M "$inputfile".mp4
ffmpeg -y -i "$inputfile" -pass 3 -b:v 0.7M "$inputfile".mp4
ffmpeg -i "$inputfile".mp4 -c:v libvpx -b:v 0.7M -strict -2 "$inputfile".webm